#!/usr/bin/env python3
"""
Enterprise Architecture Orchestration Runtime
Implements EngineRuntime from shared engine framework!
"""
from __future__ import annotations
import logging
from typing import Optional, Any, Dict
from datetime import datetime
import hashlib

from shared.engine.runtime import EngineRuntime
from shared.engine.context import EngineContext
from shared.engine.result import EngineResult, EngineStatus
from shared.engine.manifest import ExecutionManifest, EngineMetadata, ExecutionDetails, ArtifactDetails
from shared.engine.diagnostics import EngineDiagnostic, EngineDiagnosticSeverity
from shared.serialization.canonical import canonical_json

from eis.contracts.intelligence_package import EnterpriseIntelligencePackage
from eaeo.contracts.mission_contract import (
    MissionContract,
    MissionContractMetadata,
    Mission,
    Objective,
    Task
)
from eaeo.internal.evidence import MissionEvidence


logger = logging.getLogger(__name__)


class EnterpriseArchitectureOrchestrationRuntime(
    EngineRuntime[EnterpriseIntelligencePackage, MissionContract, MissionEvidence]
):
    """
    EAEO's runtime implementing EngineRuntime
    """

    def get_engine_metadata(self) -> EngineMetadata:
        """
        Return static EAEO metadata
        """
        return EngineMetadata(
            engine_id="eaeo",
            engine_name="Enterprise Architecture and Execution Orchestration",
            engine_version="1.0.0",
            contract_version="1.0.0",
            capabilities=["plan", "orchestrate", "create_mission_contract"]
        )

    def execute(
        self,
        input_artifact: EnterpriseIntelligencePackage,
        context: Optional[EngineContext] = None,
        **kwargs: Any
    ) -> EngineResult[MissionContract, MissionEvidence]:
        """
        Execute EAEO: transform EnterpriseIntelligencePackage into MissionContract
        """
        start_time = datetime.utcnow()
        engine_ctx = context or EngineContext()
        diagnostics: list[EngineDiagnostic] = []

        try:
            # Create execution manifest
            exec_manifest = ExecutionManifest(
                engine_metadata=self.get_engine_metadata(),
                execution=ExecutionDetails(
                    correlation_id=engine_ctx.correlation_id,
                    started_at=start_time
                )
            )

            # Initialize evidence
            evidence = MissionEvidence(
                execution_id=exec_manifest.execution.execution_id,
                started_at=start_time,
                configuration=kwargs.get("configuration", {})
            )

            # Create MissionContract (for now, sample implementation!)
            # In a real implementation, we would process insights/recommendations
            # from the EnterpriseIntelligencePackage!
            contract_meta = MissionContractMetadata(
        name=f"Mission Contract from {input_artifact.manifest.package_id}"
    )
            sample_mission = Mission(
                name="Sample Mission",
                description="Mission generated by EAEO from Enterprise Intelligence"
            )
            sample_objective = Objective(
                name="Sample Objective"
            )
            sample_task = Task(
                name="Sample Task"
            )
            sample_objective.tasks.append(sample_task)
            sample_mission.objectives.append(sample_objective)
            mission_contract = MissionContract(
                metadata=contract_meta,
                missions=[sample_mission]
            )
            mission_contract.content_hash = mission_contract.compute_content_hash()

            # Update evidence
            evidence.mission_ids = [m.mission_id for m in mission_contract.missions]
            for mission in mission_contract.missions:
                evidence.objective_ids.extend([o.objective_id for o in mission.objectives])

            # Update manifest
            end_time = datetime.utcnow()
            exec_manifest.execution.finished_at = end_time
            exec_manifest.execution.duration_seconds = (end_time - start_time).total_seconds()
            exec_manifest.execution.status = "success"
            exec_manifest.artifacts.output_artifact_hash = mission_contract.content_hash
            if input_artifact.content_hash:
                exec_manifest.artifacts.input_artifact_hash = input_artifact.content_hash
            # Set evidence id and hash
            exec_manifest.artifacts.evidence_id = exec_manifest.execution.execution_id
            exec_manifest.artifacts.evidence_hash = hashlib.sha256(
                canonical_json(evidence.to_dict()).encode("utf-8")
            ).hexdigest()
            exec_manifest.metrics = {
                "num_missions": len(mission_contract.missions),
                "num_objectives": sum(len(m.objectives) for m in mission_contract.missions),
                "num_tasks": sum(
                    len(o.tasks) for m in mission_contract.missions for o in m.objectives
                )
            }
            evidence.finished_at = end_time

            return EngineResult(
                status=EngineStatus.SUCCESS,
                manifest=exec_manifest,
                output_artifact=mission_contract,
                diagnostics=diagnostics,
                evidence=evidence,
                metrics=exec_manifest.metrics,
                duration_seconds=exec_manifest.execution.duration_seconds
            )

        except Exception as e:
            end_time = datetime.utcnow()
            error_diag = EngineDiagnostic(
                code="EAEO-001",
                severity=EngineDiagnosticSeverity.ERROR,
                message=str(e),
                source="EnterpriseArchitectureOrchestrationRuntime"
            )
            diagnostics.append(error_diag)

            exec_manifest = ExecutionManifest(
                engine_metadata=self.get_engine_metadata(),
                execution=ExecutionDetails(
                    correlation_id=engine_ctx.correlation_id,
                    started_at=start_time,
                    finished_at=end_time,
                    duration_seconds=(end_time - start_time).total_seconds(),
                    status="failure"
                ),
                metrics={
                    "duration_seconds": (end_time - start_time).total_seconds()
                }
            )

            return EngineResult(
                status=EngineStatus.FAILURE,
                manifest=exec_manifest,
                output_artifact=None,
                diagnostics=diagnostics,
                evidence=None,
                metrics=exec_manifest.metrics,
                duration_seconds=exec_manifest.execution.duration_seconds
            )

    def replay(self, manifest: ExecutionManifest, **kwargs: Any) -> EngineResult[MissionContract, MissionEvidence]:
        raise NotImplementedError("Replay not yet implemented for EAEO!")
