#!/usr/bin/env python3
"""
Enterprise Knowledge Engine (EKE) — Projection Engine
Generates artifacts from the Canonical Object Graph (COG).
"""

from pathlib import Path
from typing import TextIO
from eke.ir import EnterpriseIR


class MarkdownDocumentationGenerator:
    def __init__(self, ir: EnterpriseIR, output_dir: Path):
        self.ir = ir
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self):
        # Generate main documentation file
        main_doc_path = self.output_dir / "enterprise_knowledge.md"
        with open(main_doc_path, "w") as f:
            self._write_header(f)
            self._write_objects_section(f)
            self._write_relationships_section(f)
        print(f"📄 Generated documentation at {main_doc_path}")

    def _write_header(self, f: TextIO):
        f.write("# Enterprise Knowledge Graph\n\n")
        f.write("Generated by EKL Projection Engine\n\n")

    def _write_objects_section(self, f: TextIO):
        f.write("## Canonical Objects\n\n")
        if not self.ir.objects:
            f.write("No objects found.\n\n")
            return

        # Group objects by type
        objects_by_type = {}
        for obj in self.ir.objects.values():
            obj_type = obj.type
            if obj_type not in objects_by_type:
                objects_by_type[obj_type] = []
            objects_by_type[obj_type].append(obj)

        for obj_type, objects in sorted(objects_by_type.items()):
            f.write(f"### {obj_type}\n\n")
            for obj in sorted(objects, key=lambda o: o.id):
                f.write(f"- **{obj.id}**\n")
                # Write description if available
                if obj.description:
                    f.write(f"  - {obj.description}\n")
                f.write("\n")

    def _write_relationships_section(self, f: TextIO):
        f.write("## Relationships\n\n")
        if not self.ir.relationships:
            f.write("No relationships found.\n\n")
            return

        # Separate explicit and derived
        explicit_rels = []
        derived_rels = []
        for rel in self.ir.relationships.values():
            if "derived:" in rel.id:
                derived_rels.append(rel)
            else:
                explicit_rels.append(rel)

        if explicit_rels:
            f.write("### Explicit Relationships\n\n")
            for rel in sorted(explicit_rels, key=lambda r: r.id):
                f.write(f"- **{rel.id}**: {rel.type} from `{rel.source}` to `{rel.target}`\n")

        if derived_rels:
            f.write("\n### Derived Relationships (Inferred by Reasoning Engine)\n\n")
            for rel in sorted(derived_rels, key=lambda r: r.id):
                f.write(f"- **{rel.id}**: {rel.type} from `{rel.source}` to `{rel.target}`\n")
