import assert from "node:assert/strict";
import test from "node:test";

import { buildGateCStatusProjection } from "../src/commands/gate-c.js";

test("Gate C status projection surfaces specification system readout", () => {
  const projection = buildGateCStatusProjection();
  const sourceArtifacts = projection.source_artifacts as Record<string, unknown>;
  const governancePlatform = projection.governance_platform as Record<
    string,
    unknown
  >;
  const capabilityGraph = governancePlatform.capability_graph as Record<
    string,
    unknown
  >;
  const specificationSystem = governancePlatform.specification_system as Record<
    string,
    unknown
  >;
  const decisionQuality = governancePlatform.decision_quality as Record<
    string,
    unknown
  >;
  const learningIntelligence = governancePlatform.learning_intelligence as Record<
    string,
    unknown
  >;
  const evidenceConvergence = governancePlatform.evidence_convergence as Record<
    string,
    unknown
  >;
  const overall = projection.overall as Record<string, unknown>;
  const capabilityGraphHealthDomains = capabilityGraph.health_domains as Record<
    string,
    unknown
  >;
  const structuralHealth = capabilityGraphHealthDomains.structural as Record<
    string,
    unknown
  >;
  const architecturalHealth =
    capabilityGraphHealthDomains.architectural as Record<string, unknown>;
  const evidenceHealth =
    capabilityGraphHealthDomains.evidence as Record<string, unknown>;

  assert.equal(typeof specificationSystem.status, "string");
  assert.equal(
    overall.specification_system_status,
    specificationSystem.status,
  );
  assert.equal(
    overall.specification_conformance_status,
    specificationSystem.conformance_status,
  );
  assert.equal(
    overall.specification_vocabulary_status,
    specificationSystem.vocabulary_status,
  );
  assert.equal(
    overall.specification_registry_artifact_count,
    specificationSystem.registry_artifact_count,
  );
  assert.equal(
    overall.specification_registry_edge_count,
    specificationSystem.registry_edge_count,
  );
  assert.equal(overall.specification_rfc_count, specificationSystem.rfc_count);
  assert.equal(overall.specification_conf_count, specificationSystem.conf_count);
  assert.equal(
    overall.specification_spec_count,
    specificationSystem.spec_count,
  );
  assert.equal(
    overall.specification_conformance_warning_count,
    specificationSystem.conformance_warning_count,
  );
  assert.equal(
    overall.specification_conformance_failure_count,
    specificationSystem.conformance_failure_count,
  );
  assert.equal(
    overall.specification_vocabulary_term_count,
    specificationSystem.vocabulary_term_count,
  );
  assert.equal(
    overall.specification_vocabulary_duplicate_count,
    specificationSystem.vocabulary_duplicate_count,
  );
  assert.equal(overall.decision_quality_status, decisionQuality.status);
  assert.equal(
    overall.decision_quality_decision_count,
    decisionQuality.decision_count,
  );
  assert.equal(
    overall.decision_quality_traceability_coverage,
    decisionQuality.decision_traceability_coverage,
  );
  assert.equal(
    overall.decision_quality_outcome_coverage,
    decisionQuality.decision_outcome_coverage,
  );
  assert.equal(
    overall.decision_quality_learning_closure,
    decisionQuality.decision_learning_closure,
  );
  assert.equal(
    overall.decision_quality_reproducibility,
    decisionQuality.decision_reproducibility,
  );
  assert.equal(
    overall.decision_quality_reversibility,
    decisionQuality.decision_reversibility,
  );
  assert.equal(
    overall.decision_quality_impact_graph_completeness,
    decisionQuality.decision_impact_graph_completeness,
  );
  assert.equal(
    overall.decision_quality_engineering_leverage_measurement_coverage,
    decisionQuality.engineering_leverage_measurement_coverage,
  );
  assert.equal(
    overall.decision_quality_effectiveness,
    decisionQuality.decision_effectiveness,
  );
  assert.equal(
    overall.decision_quality_success_rate,
    decisionQuality.decision_success_rate,
  );
  assert.equal(
    overall.decision_quality_false_decision_rate,
    decisionQuality.false_decision_rate,
  );
  assert.equal(
    overall.decision_quality_reversal_rate,
    decisionQuality.decision_reversal_rate,
  );
  assert.equal(
    overall.decision_quality_evidence_utilization_rate,
    decisionQuality.evidence_utilization_rate,
  );
  assert.equal(
    overall.decision_quality_knowledge_reuse_rate,
    decisionQuality.knowledge_reuse_rate,
  );
  assert.equal(
    overall.decision_quality_evidence_strength_index,
    decisionQuality.evidence_strength_index,
  );
  assert.equal(
    overall.decision_quality_outcome_improvement_rate,
    decisionQuality.outcome_improvement_rate,
  );
  assert.equal(
    overall.decision_quality_decision_confidence_index,
    decisionQuality.decision_confidence_index,
  );
  assert.equal(
    overall.decision_quality_knowledge_weighted_quality_index,
    decisionQuality.knowledge_weighted_quality_index,
  );
  assert.equal(
    overall.decision_quality_mean_time_to_outcome_ms,
    decisionQuality.mean_time_to_outcome_ms,
  );
  assert.equal(
    overall.decision_quality_learning_velocity_ms,
    decisionQuality.learning_velocity_ms,
  );
  assert.equal(
    overall.decision_quality_confidence_growth,
    decisionQuality.decision_confidence_growth,
  );
  assert.equal(
    overall.learning_intelligence_status,
    learningIntelligence.status,
  );
  assert.equal(
    overall.learning_intelligence_decision_count,
    learningIntelligence.decision_count,
  );
  assert.equal(
    overall.learning_intelligence_outcome_count,
    learningIntelligence.outcome_count,
  );
  assert.equal(
    overall.learning_intelligence_outcome_registry_coverage,
    learningIntelligence.outcome_registry_coverage,
  );
  assert.equal(
    overall.learning_intelligence_decision_quality_index,
    learningIntelligence.decision_quality_index,
  );
  assert.equal(
    overall.learning_intelligence_learning_velocity_ms,
    learningIntelligence.learning_velocity_ms,
  );
  assert.equal(
    overall.learning_intelligence_knowledge_gain_units,
    learningIntelligence.knowledge_gain_units,
  );
  assert.equal(
    overall.learning_intelligence_knowledge_gain,
    learningIntelligence.knowledge_gain,
  );
  assert.equal(
    overall.learning_intelligence_knowledge_object_count,
    learningIntelligence.knowledge_object_count,
  );
  assert.equal(
    overall.learning_intelligence_operationalized_knowledge_count,
    learningIntelligence.operationalized_knowledge_count,
  );
  assert.equal(
    overall.learning_intelligence_knowledge_availability_rate,
    learningIntelligence.knowledge_availability_rate,
  );
  assert.equal(
    overall.learning_intelligence_knowledge_reuse_rate,
    learningIntelligence.knowledge_reuse_rate,
  );
  assert.equal(
    overall.learning_intelligence_reused_knowledge_object_count,
    learningIntelligence.reused_knowledge_object_count,
  );
  assert.equal(
    overall.learning_intelligence_improved_knowledge_object_count,
    learningIntelligence.improved_knowledge_object_count,
  );
  assert.equal(
    overall.learning_intelligence_knowledge_lineage_count,
    learningIntelligence.knowledge_lineage_count,
  );
  assert.deepEqual(
    overall.learning_intelligence_knowledge_lineage_preview,
    learningIntelligence.knowledge_lineage_preview,
  );
  assert.equal(
    overall.learning_intelligence_recommendation_effectiveness_rate,
    learningIntelligence.recommendation_effectiveness_rate,
  );
  assert.equal(
    overall.learning_intelligence_decision_pattern_change_rate,
    learningIntelligence.decision_pattern_change_rate,
  );
  assert.equal(
    overall.learning_intelligence_recommendation_acceptance_rate,
    learningIntelligence.recommendation_acceptance_rate,
  );
  assert.equal(
    overall.learning_intelligence_behavior_change_rate,
    learningIntelligence.behavior_change_rate,
  );
  assert.equal(
    overall.learning_intelligence_engineering_leverage_ratio,
    learningIntelligence.engineering_leverage_ratio,
  );
  assert.equal(
    overall.learning_intelligence_repeated_mistake_count,
    learningIntelligence.repeated_mistake_count,
  );
  assert.equal(
    overall.learning_intelligence_future_decision_improvement_rate,
    learningIntelligence.future_decision_improvement_rate,
  );
  assert.equal(
    overall.evidence_convergence_status,
    evidenceConvergence.status,
  );
  assert.equal(
    overall.evidence_producer_count,
    evidenceConvergence.producer_count,
  );
  assert.equal(
    overall.evidence_target_producer_count,
    evidenceConvergence.target_producer_count,
  );
  assert.equal(
    overall.evidence_registered_target_producer_count,
    evidenceConvergence.registered_target_producer_count,
  );
  assert.equal(
    overall.evidence_target_coverage_ratio,
    evidenceConvergence.target_coverage_ratio,
  );
  const closedLoopHypothesis =
    governancePlatform.closed_loop_hypothesis as Record<string, unknown>;
  const closedLoopStages =
    closedLoopHypothesis.stages as Record<string, Record<string, unknown>>;
  assert.equal(
    closedLoopHypothesis.statement,
    "Evidence -> Decision -> Outcome -> Learning -> Knowledge -> Better Decision -> Better Outcome",
  );
  assert.deepEqual(overall.closed_loop_hypothesis, closedLoopHypothesis);
  assert.equal(closedLoopStages.decision?.metric, decisionQuality.decision_count);
  assert.equal(
    closedLoopStages.knowledge?.metric,
    learningIntelligence.knowledge_availability_rate,
  );
  assert.equal(
    overall.capability_graph_structural_health_status,
    structuralHealth.status,
  );
  assert.equal(
    overall.capability_graph_architectural_health_status,
    architecturalHealth.status,
  );
  assert.equal(
    overall.capability_graph_cycle_count,
    structuralHealth.cycle_count,
  );
  assert.equal(
    overall.capability_graph_forbidden_dependency_count,
    architecturalHealth.forbidden_dependency_count,
  );
  assert.equal(
    overall.capability_graph_layering_violation_count,
    architecturalHealth.layering_violation_count,
  );
  assert.equal(
    overall.capability_graph_abstraction_leak_count,
    architecturalHealth.abstraction_leak_count,
  );
  assert.equal(
    overall.capability_graph_orphan_capability_count,
    structuralHealth.orphan_capability_count,
  );
  assert.equal(
    overall.capability_graph_evidence_health_status,
    evidenceHealth.status,
  );
  assert.equal(
    overall.capability_graph_capability_without_evidence_count,
    evidenceHealth.capability_without_evidence_count,
  );
  assert.equal(
    overall.capability_graph_stale_evidence_count,
    evidenceHealth.stale_evidence_count,
  );
  assert.equal(
    overall.capability_graph_unverifiable_capability_count,
    evidenceHealth.unverifiable_capability_count,
  );
  assert.equal(
    overall.capability_graph_orphaned_evidence_count,
    evidenceHealth.orphaned_evidence_count,
  );
  assert.equal(
    overall.capability_graph_inconsistent_evidence_count,
    evidenceHealth.inconsistent_evidence_count,
  );
  assert.equal(
    overall.capability_graph_unsigned_evidence_count,
    evidenceHealth.unsigned_evidence_count,
  );
  assert.equal(
    overall.capability_graph_tampered_evidence_count,
    evidenceHealth.tampered_evidence_count,
  );
  assert.equal(
    overall.capability_graph_partial_evidence_count,
    evidenceHealth.partial_evidence_count,
  );
  assert.equal(
    overall.capability_graph_superseded_evidence_count,
    evidenceHealth.superseded_evidence_count,
  );
  assert.equal(
    overall.capability_graph_expired_evidence_count,
    evidenceHealth.expired_evidence_count,
  );

  assert.match(
    String(sourceArtifacts.specification_conformance_ref),
    /specification-conformance-report\.json$/,
  );
  assert.match(
    String(sourceArtifacts.specification_artifact_graph_ref),
    /specification-artifact-graph\.json$/,
  );
  assert.match(
    String(sourceArtifacts.specification_vocabulary_audit_ref),
    /specification-vocabulary-audit\.json$/,
  );
  assert.match(
    String(specificationSystem.conformance_ref),
    /specification-conformance-report\.json$/,
  );
  assert.match(
    String(specificationSystem.artifact_graph_ref),
    /specification-artifact-graph\.json$/,
  );
  assert.match(
    String(specificationSystem.vocabulary_audit_ref),
    /specification-vocabulary-audit\.json$/,
  );
  assert.match(
    String(decisionQuality.report_ref),
    /decision-quality-report\.json$/,
  );
  assert.match(
    String(sourceArtifacts.learning_intelligence_ref),
    /learning-intelligence-report\.json$/,
  );
  assert.match(
    String(learningIntelligence.report_ref),
    /learning-intelligence-report\.json$/,
  );
  assert.match(
    String(evidenceConvergence.report_ref),
    /evidence-producer-convergence-report\.json$/,
  );
});
