"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultRequirementVerificationStatus = exports.defaultRequirementStatus = exports.defaultRequirementPriority = exports.newRequirementId = exports.RequirementRepositoryInMemory = exports.RequirementRepositoryFileBacked = exports.RequirementRepositoryCurrent = void 0;
var requirement_repository_1 = require("./requirement.repository");
Object.defineProperty(exports, "RequirementRepositoryCurrent", { enumerable: true, get: function () { return requirement_repository_1.RequirementRepositoryCurrent; } });
Object.defineProperty(exports, "RequirementRepositoryFileBacked", { enumerable: true, get: function () { return requirement_repository_1.RequirementRepositoryFileBacked; } });
Object.defineProperty(exports, "RequirementRepositoryInMemory", { enumerable: true, get: function () { return requirement_repository_1.RequirementRepositoryInMemory; } });
Object.defineProperty(exports, "newRequirementId", { enumerable: true, get: function () { return requirement_repository_1.newRequirementId; } });
Object.defineProperty(exports, "defaultRequirementPriority", { enumerable: true, get: function () { return requirement_repository_1.defaultRequirementPriority; } });
Object.defineProperty(exports, "defaultRequirementStatus", { enumerable: true, get: function () { return requirement_repository_1.defaultRequirementStatus; } });
Object.defineProperty(exports, "defaultRequirementVerificationStatus", { enumerable: true, get: function () { return requirement_repository_1.defaultRequirementVerificationStatus; } });
