import type {
  TraceabilityArtifact,
  TraceabilityArtifactRepository,
} from "../contracts";

const ARTIFACTS: readonly TraceabilityArtifact[] = Object.freeze([
  {
    id: "capability-eos-001",
    title: "EOS-001 Requirement Management",
    description: "Execution graph anchor for delivered requirement management.",
    kind: "capability",
    reference: "enterprise/execution/CAPABILITY-REGISTRY.yaml",
    referenceKind: "repo_path",
    requirementIds: ["req-001", "req-002"],
    linkedCapabilityIds: ["EOS-001"],
    verification: "not_applicable",
  },
  {
    id: "api-requirements-collection",
    title: "Requirements Collection API",
    description: "Creates and searches requirement aggregates.",
    kind: "api",
    reference: "/api/requirements",
    referenceKind: "api_route",
    requirementIds: ["req-001"],
    linkedCapabilityIds: ["EOS-001"],
    verification: "passed",
  },
  {
    id: "api-requirements-item",
    title: "Requirement Lifecycle API",
    description: "Reads and advances requirement lifecycle transitions.",
    kind: "api",
    reference: "/api/requirements/:id",
    referenceKind: "api_route",
    requirementIds: ["req-002"],
    linkedCapabilityIds: ["EOS-001"],
    verification: "passed",
  },
  {
    id: "source-requirement-service",
    title: "Requirement Management Service",
    description: "Canonical service surface for requirement lifecycle operations.",
    kind: "source",
    reference:
      "workspace/capabilities/requirement-management/implementation/services/requirement.service.ts",
    referenceKind: "repo_path",
    requirementIds: ["req-001", "req-002"],
    linkedCapabilityIds: ["EOS-001"],
    verification: "not_applicable",
  },
  {
    id: "test-requirement-management",
    title: "Requirement Management Tests",
    description: "Verifies requirement lifecycle and search behaviors.",
    kind: "test",
    reference:
      "workspace/capabilities/requirement-management/tests/requirement-management.test.ts",
    referenceKind: "repo_path",
    requirementIds: ["req-001", "req-002", "req-003"],
    linkedCapabilityIds: ["EOS-001", "EOS-002"],
    verification: "passed",
  },
  {
    id: "spec-req-0001",
    title: "REQ-0001 Canonical Requirement Specification",
    description: "Frozen requirement specification that anchors traceability identity.",
    kind: "specification",
    reference: "workspace/examples/vertical-slice/REQ-0001/req-0001.els.yaml",
    referenceKind: "repo_path",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002", "EOS-003"],
    verification: "passed",
    externalRequirementRefs: ["REQ-0001"],
  },
  {
    id: "evidence-req-0001-eir",
    title: "REQ-0001 EIR Output",
    description: "Transformation output proving identity propagation from the canonical requirement.",
    kind: "evidence",
    reference: "workspace/examples/vertical-slice/REQ-0001/eir-output/REQ-0001.eir.json",
    referenceKind: "repo_path",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002", "EOS-003"],
    verification: "passed",
    externalRequirementRefs: ["REQ-0001"],
  },
  {
    id: "capability-eos-002",
    title: "EOS-002 Requirements Traceability Matrix",
    description: "Execution graph anchor for RTM delivery.",
    kind: "capability",
    reference: "enterprise/execution/CAPABILITY-REGISTRY.yaml",
    referenceKind: "repo_path",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002"],
    verification: "not_applicable",
  },
  {
    id: "api-rtm-collection",
    title: "RTM Collection API",
    description: "Searches matrix rows across requirements and delivery artifacts.",
    kind: "api",
    reference: "/api/rtm",
    referenceKind: "api_route",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002"],
    verification: "passed",
  },
  {
    id: "api-rtm-item",
    title: "RTM Detail API",
    description: "Returns a single traceability row for a requirement.",
    kind: "api",
    reference: "/api/rtm/:id",
    referenceKind: "api_route",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002"],
    verification: "passed",
  },
  {
    id: "source-rtm-service",
    title: "RTM Service",
    description: "Builds the derived traceability matrix from requirements and artifacts.",
    kind: "source",
    reference:
      "workspace/capabilities/requirements-traceability-matrix/implementation/services/traceability.service.ts",
    referenceKind: "repo_path",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002"],
    verification: "not_applicable",
  },
  {
    id: "test-rtm",
    title: "RTM Capability Tests",
    description: "Verifies matrix assembly, filtering, and evidence linking.",
    kind: "test",
    reference:
      "workspace/capabilities/requirements-traceability-matrix/tests/requirements-traceability-matrix.test.ts",
    referenceKind: "repo_path",
    requirementIds: ["req-003"],
    linkedCapabilityIds: ["EOS-002"],
    verification: "passed",
  },
  // REQ-011 Traceability Artifacts
  {
    id: "api-requirements-proof",
    title: "Requirement Proof API",
    description: "Returns verification proof data for a requirement.",
    kind: "api",
    reference: "/api/requirements/:id/proof",
    referenceKind: "api_route",
    requirementIds: ["req-011"],
    linkedCapabilityIds: ["EOS-requirement-management", "EOS-evidence-registry"],
    verification: "passed",
    externalRequirementRefs: ["REQ-011"],
  },
  {
    id: "source-verification-proof-panel",
    title: "Verification Proof Panel Component",
    description: "React component that displays requirement traceability and evidence.",
    kind: "source",
    reference:
      "workspace/capabilities/requirement-management/experience/components/VerificationProofPanel.tsx",
    referenceKind: "repo_path",
    requirementIds: ["req-011"],
    linkedCapabilityIds: ["EOS-requirement-management", "EOS-evidence-registry", "EOS-governance-verification"],
    verification: "passed",
    externalRequirementRefs: ["REQ-011"],
  },
  {
    id: "evidence-req-011-static",
    title: "REQ-011 Static Evidence Files",
    description: "Static fallback data for REQ-011 requirement and proof.",
    kind: "evidence",
    reference: "workspace/apps/web/public/.eos/evidence/REQ-011/",
    referenceKind: "repo_path",
    requirementIds: ["req-011"],
    linkedCapabilityIds: ["EOS-requirement-management", "EOS-evidence-registry"],
    verification: "passed",
    externalRequirementRefs: ["REQ-011"],
  },
  {
    id: "page-requirements-detail",
    title: "Requirement Detail Page",
    description: "Next.js page that renders the VerificationProofPanel for any requirement.",
    kind: "source",
    reference:
      "workspace/apps/web/app/requirements/[id]/page.tsx",
    referenceKind: "repo_path",
    requirementIds: ["req-011"],
    linkedCapabilityIds: ["EOS-requirement-management"],
    verification: "passed",
    externalRequirementRefs: ["REQ-011"],
  },
  {
    id: "test-verification-proof-panel",
    title: "Verification Proof Panel Tests",
    description: "Tests for the VerificationProofPanel component that verify traceability and evidence display functionality.",
    kind: "test",
    reference: "workspace/capabilities/requirement-management/tests/verification-proof-panel.test.tsx",
    referenceKind: "repo_path",
    requirementIds: ["req-011"],
    linkedCapabilityIds: ["EOS-requirement-management", "EOS-governance-verification"],
    verification: "passed",
    externalRequirementRefs: ["REQ-011"],
  },
  {
    id: "source-location-filter-component",
    title: "Location Filter Component",
    description: "React component for location filtering on community page, integrated with BaseSearchBar.",
    kind: "source",
    reference: "workspace/.eos/evidence/location-filter.tsx",
    referenceKind: "repo_path",
    requirementIds: ["req-010"],
    linkedCapabilityIds: ["EOS-community", "EOS-filtering", "EOS-ui-components"],
    verification: "passed",
    externalRequirementRefs: ["REQ-010"],
  },
  {
    id: "source-community-page",
    title: "Community Page Implementation",
    description: "Community page with integrated location filter and search functionality.",
    kind: "source",
    reference: "workspace/.eos/evidence/community-page.tsx",
    referenceKind: "repo_path",
    requirementIds: ["req-010"],
    linkedCapabilityIds: ["EOS-community", "EOS-filtering", "EOS-ui-components"],
    verification: "passed",
    externalRequirementRefs: ["REQ-010"],
  },
  {
    id: "test-location-filter",
    title: "Location Filter Tests",
    description: "Tests for the LocationFilter component that verify filtering functionality and interactions.",
    kind: "test",
    reference: "workspace/.eos/evidence/location-filter.test.tsx",
    referenceKind: "repo_path",
    requirementIds: ["req-010"],
    linkedCapabilityIds: ["EOS-community", "EOS-filtering", "EOS-governance-verification"],
    verification: "passed",
    externalRequirementRefs: ["REQ-010"],
  },
  {
    id: "evidence-req-010-static",
    title: "REQ-010 Static Evidence Files",
    description: "Static fallback data for REQ-010 requirement and proof.",
    kind: "evidence",
    reference: "workspace/.eos/evidence/",
    referenceKind: "repo_path",
    requirementIds: ["req-010"],
    linkedCapabilityIds: ["EOS-community", "EOS-filtering", "EOS-evidence-registry"],
    verification: "passed",
    externalRequirementRefs: ["REQ-010"],
  },
]);

function cloneArtifact(artifact: TraceabilityArtifact): TraceabilityArtifact {
  return {
    ...artifact,
    requirementIds: [...artifact.requirementIds],
    linkedCapabilityIds: [...artifact.linkedCapabilityIds],
    ...(artifact.externalRequirementRefs !== undefined
      ? { externalRequirementRefs: [...artifact.externalRequirementRefs] }
      : {}),
  };
}

export const TraceabilityArtifactRepositoryInMemory: TraceabilityArtifactRepository = {
  kind: "repository",
  entityName: "TraceabilityArtifact",
  list() {
    return ARTIFACTS.map(cloneArtifact);
  },
} as const;