/**
 * B6.3 GOLDEN PROOF RUNNER (MINIMAL OUTPUT — SESUAI SPESIFIKASI USER)
 *
 * Output format DIPERTAHANKAN sesuai spec B6.3:
 *   DECISION
 *   D = dec-...
 *
 *   EXECUTION
 *   R = <actual runtime execution_id>
 *
 *   OWNERSHIP
 *   R generated by = Python runtime
 *
 *   PERSISTENCE
 *   D + R found in durable evidence
 *
 *   TRACE
 *   trace(D) = [R]
 *
 *   INVARIANT
 *   D != R
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import {
  recordRuntimeInvocation,
  traceExecutionByDecision,
} from "../packages/core/runtime/src/invocation-evidence.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const EOS_ROOT = resolve(__dirname, "..", "..");
const IMPL_DIR = join(EOS_ROOT, "implementation");

const EVIDENCE_PATH = "/tmp/eos-b63-final-evidence.jsonl";
process.env.EOS_RUNTIME_INVOCATION_EVIDENCE_PATH = EVIDENCE_PATH;
process.env.EOS_RUNTIME_INVOCATION_PRODUCT_ID = "eos-b63-final-001";
if (existsSync(EVIDENCE_PATH)) rmSync(EVIDENCE_PATH);
mkdirSync(dirname(EVIDENCE_PATH), { recursive: true });

// D = decision_id (Gate 5 output)
const D = `dec-${randomUUID().slice(0, 12)}`;
const SUBJECT = "knowledge/gate6-b63";
const OPERATION = "eke:compile";

// Actual artifact
const TMP_ROOT = mkdtempSync(join(tmpdir(), "eos-b63-"));
const INPUT_PKG_DIR = join(TMP_ROOT, "src");
mkdirSync(INPUT_PKG_DIR, { recursive: true });
writeFileSync(join(INPUT_PKG_DIR, "p.json"), JSON.stringify({ name: "b63", v: "1" }));
writeFileSync(join(INPUT_PKG_DIR, "r.md"), "# B63\n");

// ============================================================
// EXECUTION BOUNDARY (spawnSync = pattern existing governance-runtime.runCommand)
// ============================================================
const PYTHON_SCRIPT = `
import sys, json
from pathlib import Path
sys.path.insert(0, "${IMPL_DIR.replace(/\\/g, "/")}")
from eke.internal.engine.runtime import EnterpriseKnowledgeEngineRuntime
from shared.engine.context import EngineContext
rt = EnterpriseKnowledgeEngineRuntime()
ctx = EngineContext()
ctx.correlation_id = "${D}"
res = rt.execute(Path(r"${INPUT_PKG_DIR.replace(/\\/g, "/")}"), context=ctx)
m = res.manifest.to_dict()
print(json.dumps({
  "status": getattr(res.status, "value", str(res.status)),
  "eid": m["execution"]["execution_id"],
  "mid": m["execution"]["manifest_id"],
  "st":  m["execution"]["started_at"],
  "fi":  m["execution"]["finished_at"],
  "du":  m["execution"]["duration_seconds"],
  "es":  m["execution"]["status"],
  "oh":  m["artifacts"]["output_artifact_hash"],
  "evid":m["artifacts"]["evidence_id"],
}, default=str))
`;

const proc = spawnSync("python3", ["-c", PYTHON_SCRIPT], { encoding: "utf8", timeout: 30_000, stdio: ["ignore", "pipe", "pipe"] });
if (proc.status !== 0) {
  process.stderr.write("RUNTIME EXEC FAILED\n" + proc.stderr);
  process.exit(1);
}
let payload: Record<string, unknown>;
try {
  payload = JSON.parse((proc.stdout ?? "").trim()) as Record<string, unknown>;
} catch {
  process.stderr.write("PAYLOAD PARSE FAILED\n" + proc.stdout);
  process.exit(1);
}

const R = payload.eid as string;
const R_FROM = "Python EKE runtime (ExecutionDetails.default_factory uuid4)";

// ============================================================
// PERSIST D + R pair (R dari runtime receipt, BUKAN dari input)
// ============================================================
const INPUT_ACTUAL = {
  operation: OPERATION,
  subject: SUBJECT,
  artifact_path: INPUT_PKG_DIR,
  decision_id: D,
  correlation_id: D,
  // no execution_id here
};
const RESULT_ACTUAL = {
  operation: OPERATION,
  subject: SUBJECT,
  execution_id: R,
  manifest_id: payload.mid,
  started_at: payload.st,
  finished_at: payload.fi,
  duration_seconds: payload.du,
  execution_status: payload.es,
  output_artifact_hash: payload.oh,
  evidence_id: payload.evid,
};
const SUCCESS = payload.es === "success";
recordRuntimeInvocation({
  capabilityId: "eke-runtime",
  operationId: "compile",
  sourceRef: "B63Final.spawnSyncEke",
  success: SUCCESS,
  input: INPUT_ACTUAL,
  result: RESULT_ACTUAL,
  productId: "eos-b63-final-001",
  decision_id: D,
});

// ============================================================
// TRACE D → [execution events], lalu direct verify D + R in same record
// ============================================================
const traceResult = traceExecutionByDecision(D);

const evidenceLines = readFileSync(EVIDENCE_PATH, "utf8").split("\n").filter((l) => l.trim());
const recsWithD = evidenceLines
  .map((ln) => { try { return JSON.parse(ln); } catch { return null; } })
  .filter((r): r is Record<string, unknown> => r !== null && (r as { decision_id?: string | null }).decision_id === D);

const pairExists = recsWithD.some((rec) => {
  const res = (rec.result as Record<string, unknown> | null) ?? null;
  return res !== null && (res.execution_id as string | undefined) === R;
});

const traceFound = traceResult.totalMatches > 0;

// ============================================================
// OUTPUT EXACT SESUAI SPESIFIKASI B6.3
// ============================================================
process.stdout.write(`DECISION
D = ${D}

EXECUTION
R = ${R}

OWNERSHIP
R generated by = ${R_FROM}

PERSISTENCE
${pairExists ? "D + R found in durable evidence" : "❌ D + R NOT found in durable evidence"}

TRACE
trace(D) = [${traceFound ? (recsWithD.length > 0 && pairExists ? R : (traceResult.matchingExecutions[0]?.runId ?? `${traceResult.totalMatches} execution record(s) linked to D`)) : ""}]

INVARIANT
${D !== R ? "D != R" : "❌ D == R (VIOLATION)"}
`);

// Exit non-zero kalau ada yang gagal, supaya caller tahu.
const ok = pairExists && traceFound && D !== R && SUCCESS;
process.exit(ok ? 0 : 2);
