packages:
  - "apps/*"
  - "packages/core/*"
  - "packages/compositions/*"
  - "packages/presentation/*"
  - "packages/composition"
  - "config/*"
  - "packages/tooling/*"
  - "products/*"
  - "capabilities/*"