packages:
  - apps/*
  - packages/core/*
  - packages/compositions/*
  - packages/presentation/*
  - config/*
  - packages/tooling/*
  - products/*
  - capabilities/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
